### ISSUE TITLE
Using the default "l" command caused the table to become skewed by TableParser

### ISSUE THREAD

**Issue by AugustYadon** [neekey/ps#18]
I got bad output using OS X Yosemite version 10.10.5 (14F27) with this doing a simple PID lookup. When I removed the "l" parameter that is hardcoded in, I was able to get the proper output, even though it's much less output.

I don't know if anyone else has experienced this. But I have version 0.1.2 installed.

old output of a process:
 UID: [ '407128372' ],
    PID: [ '2', '70505' ],
    PPID: [ '70505', '70504' ],
    CPU: [ '70504' ],
    PRI: [ '0' ],
    NI: [ '31', '0' ],
    VSZ: [ '2464092' ],
    RSS: [ '692' ],
    WCHAN: [ '692', '-' ],
    STAT: [ 'S+' ],
    TT: [ '+', 's003' ],
    TIME: [ '0:00.05' ],
    COMMAND: [ '0:00.05', '-bash' ] } 

"fixed" out put of a process:
{ PID: [ '80018' ],
    TTY: [ 'ttys003' ],
    TIME: [ '0:00.53' ],
    CMD: [ 'node', 'node-site.jslib' ] }

**Comment by neekey** [comment]
@AugustYadon Sorry for the late response. It's very hard to tell just from your description since it works for everyone else. 

So for a better knowing of your situation, can you do two things for me?

- 1 clone this project to your local and run the test `npm test` to see if all test cases pass
- 2 type the ps command manually in your terminal ( with the default arguments `|`) instead of using this module, and copy the result here, so that I can figure what caused the problem.

Thanks.

**Comment by neekey** [comment]
close due to inactive
