### ISSUE TITLE
Feature request: *sync alternatives.

### ISSUE THREAD

**Issue by oxygens** [neekey/ps#19]
It would be great to have the synchronous alternatives as well, for all functions.

**Comment by neekey** [comment]
@oxygens Thanks for your suggestion, but synchronous is not the way I want this module to be. Since synchronous function has a lower performance, and it's better to use Promise.

Since there's already a lot of brilliant promise libs out there and promise in ES6, I am not going to involve it in this library, since it's very easy to wrap around it:

```js
import ps from 'ps-node';

function lookup(...args) {
    return new Promise((resolve, reject) => {
        ps.lookup(...args, (err, result) => {
            if (err) return reject(err);
            return resolve(result);
        });
    });
}
```

**Comment by oxygens** [comment]
All serious modules offer both. Just saying.
